---
name: Test And Release

on:
  push:
    branches:
      - main

jobs:
  Unit_Tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache tools
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            autoit-v3-setup.exe
            SciTE4AutoIt3.exe
            C:\Program Files (x86)\AutoIt3\SciTE\Au3Stripper
          key: v3
      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -o autoit-v3-setup.exe `
            -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe -o SciTE4AutoIt3.exe `
            -sSfLO https://www.autoitscript.com/autoit3/scite/download/Au3Stripper.zip
          Expand-Archive Au3Stripper.zip "${env:ProgramFiles(x86)}\AutoIt3\SciTE\Au3Stripper"
      - name: Install tools
        run: |
          Start-Process autoit-v3-setup.exe -ArgumentList /S -NoNewWindow -Wait
          Start-Process SciTE4AutoIt3.exe -ArgumentList /S -NoNewWindow -Wait
      - name: Run Vector Tests
        run: |
          $vector86 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in Tests/TestVector.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $vector86
          $callback86 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in Tests/TestCallbackArray.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $callback86

          $vector64 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in Tests/TestVector.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $vector64
          $callback64 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in Tests/TestCallbackArray.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $callback64

          if ($vector86.ExitCode -ne 0) {
              Write-Error "[x86] $($vector86.ExitCode) Vector Unit Tests failed"
          }
          if ($callback86.ExitCode -ne 0) {
              Write-Error "[x86] $($callback86.ExitCode) CallbackArray Unit Tests failed"
          }

          if ($vector64.ExitCode -ne 0) {
              Write-Error "[x64] $($vector64.ExitCode) Vector Unit Tests failed"
          }
          if ($callback64.ExitCode -ne 0) {
              Write-Error "[x64] $($callback64.ExitCode) CallbackArray Unit Tests failed"
          }
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Prerelease"
          files: |
            README.md
            *.au3
