name: UnitTests

on: [push, pull_request, workflow_dispatch]

jobs:
  Unit_Tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache tools
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            autoit-v3-setup.exe
            SciTE4AutoIt3.exe
            C:\Program Files (x86)\AutoIt3\SciTE\Au3Stripper
          key: v3
      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -o autoit-v3-setup.exe `
            -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe -o SciTE4AutoIt3.exe `
            -sSfLO https://www.autoitscript.com/autoit3/scite/download/Au3Stripper.zip
          Expand-Archive Au3Stripper.zip "${env:ProgramFiles(x86)}\AutoIt3\SciTE\Au3Stripper"
      - name: Install tools
        run: |
          Start-Process autoit-v3-setup.exe -ArgumentList /S -NoNewWindow -Wait
          Start-Process SciTE4AutoIt3.exe -ArgumentList /S -NoNewWindow -Wait
      - name: Run Vector Tests
        run: |
          $process86 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in UtilsForAutoit/Tests/TestVector.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $process86

          $process64 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in UtilsForAutoit/Tests/TestVector.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $process64

          if ($process86.ExitCode -ne 0) {
              Write-Error "$($process86.ExitCode) Vector x86 Unit Tests x86 failed"
          }

          if ($process64.ExitCode -ne 0) {
              Write-Error "$($process64.ExitCode) Vector x64 Unit Tests x64 failed"
          }
      - name: Run Dll Tests
        run: |
          $dllProcess86 = Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /run /prod /x86 /ErrorStdOut /in UtilsForAutoit/Tests/TestDll.au3 /UserParams" -PassThru -NoNewWindow
          Wait-Process -InputObject $dllProcess86

          echo "Skipping TestDll.au3 for x64 since its not supported. yet.."

          if ($dllProcess86.ExitCode -ne 0) {
              Write-Error "$($dllProcess86.ExitCode) Unit x86 Tests x64 failed"
          }
